__title__ = 'pyfeedbacker'
__description__ = 'Python assignment marking and feedback generation tool.'
__url__ = 'https://github.com/mporcheron/pyfeedbacker'
__version__ = '1.0'
__author__ = 'Martin Porcheron'
__author_email__ = 'matin+pyfeedbacker@porcheron.uk'
__license__ = 'MIT Licence'
__copyright__ = 'Copyright 2021 Martin Porcheron'